# utm-mvp/docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-utmadmin} # Use .env or default
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-securepassword}
      POSTGRES_DB: ${POSTGRES_DB:-utmdb}
    ports:
      - "${POSTGRES_PORT:-5432}:5432" # Map to host port from .env or default
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/app:/app/app # Mount app directory for live reload
    ports:
      - "8000:8000"
    environment:
      # Pass all necessary env vars from backend/.env
      # For simplicity, you can list them here or use `env_file`
      # but ensure SECRET_KEY is set securely if committing this file (better to use .env)
      PROJECT_NAME: ${PROJECT_NAME:-UTM MVP}
      POSTGRES_SERVER: db # Service name from this docker-compose file
      POSTGRES_USER: ${POSTGRES_USER:-utmadmin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-securepassword}
      POSTGRES_DB: ${POSTGRES_DB:-utmdb}
      POSTGRES_PORT: 5432 # Port inside the docker network
      SECRET_KEY: ${SECRET_KEY:-your-super-secret-key-that-is-at-least-32-bytes-long} # CHANGE THIS!
      ALGORITHM: ${ALGORITHM:-HS256}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      BACKEND_CORS_ORIGINS: '["http://localhost:5173", "http://127.0.0.1:5173"]' # Vite default dev port
    depends_on:
      - db
    # env_file:
    #   - ./backend/.env # This will load variables from backend/.env
    restart: unless-stopped

volumes:
  postgres_data: