"""Add Drone model

Revision ID: 9b9f6efcf6ea
Revises: 0ba74885dbac
Create Date: 2025-05-23 17:06:17.051300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b9f6efcf6ea'
down_revision: Union[str, None] = '0ba74885dbac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('owner_pilot_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_pilot_id'], ['pilots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drones_id'), 'drones', ['id'], unique=False)
    op.create_index(op.f('ix_drones_model_name'), 'drones', ['model_name'], unique=False)
    op.create_index(op.f('ix_drones_serial_number'), 'drones', ['serial_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drones_serial_number'), table_name='drones')
    op.drop_index(op.f('ix_drones_model_name'), table_name='drones')
    op.drop_index(op.f('ix_drones_id'), table_name='drones')
    op.drop_table('drones')
    # ### end Alembic commands ###
