"""Add FlightPlan and Waypoint tables (with configure_mappers)

Revision ID: f070f1e67850
Revises: 9b9f6efcf6ea
Create Date: 2025-05-23 21:57:21.038708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f070f1e67850'
down_revision: Union[str, None] = '9b9f6efcf6ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restricted_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('center_latitude', sa.Float(), nullable=True),
    sa.Column('center_longitude', sa.Float(), nullable=True),
    sa.Column('radius_m', sa.Float(), nullable=True),
    sa.Column('min_altitude_m', sa.Float(), nullable=True),
    sa.Column('max_altitude_m', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restricted_zones_id'), 'restricted_zones', ['id'], unique=False)
    op.create_index(op.f('ix_restricted_zones_name'), 'restricted_zones', ['name'], unique=False)
    op.create_table('flight_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pilot_id', sa.Integer(), nullable=False),
    sa.Column('drone_id', sa.Integer(), nullable=False),
    sa.Column('planned_departure_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_arrival_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='flightstatus'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['drone_id'], ['drones.id'], name='fk_flightplan_drone_id'),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilots.id'], name='fk_flightplan_pilot_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flight_plans_id'), 'flight_plans', ['id'], unique=False)
    op.create_index('ix_flightplan_drone_id', 'flight_plans', ['drone_id'], unique=False)
    op.create_index('ix_flightplan_pilot_id', 'flight_plans', ['pilot_id'], unique=False)
    op.create_index('ix_flightplan_status', 'flight_plans', ['status'], unique=False)
    op.create_table('waypoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_plan_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude_m', sa.Float(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flight_plan_id'], ['flight_plans.id'], name='fk_waypoint_flight_plan_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_waypoint_flight_plan_id_sequence_order', 'waypoints', ['flight_plan_id', 'sequence_order'], unique=True)
    op.create_index(op.f('ix_waypoints_id'), 'waypoints', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waypoints_id'), table_name='waypoints')
    op.drop_index('ix_waypoint_flight_plan_id_sequence_order', table_name='waypoints')
    op.drop_table('waypoints')
    op.drop_index('ix_flightplan_status', table_name='flight_plans')
    op.drop_index('ix_flightplan_pilot_id', table_name='flight_plans')
    op.drop_index('ix_flightplan_drone_id', table_name='flight_plans')
    op.drop_index(op.f('ix_flight_plans_id'), table_name='flight_plans')
    op.drop_table('flight_plans')
    op.drop_index(op.f('ix_restricted_zones_name'), table_name='restricted_zones')
    op.drop_index(op.f('ix_restricted_zones_id'), table_name='restricted_zones')
    op.drop_table('restricted_zones')
    # ### end Alembic commands ###
