name: CI

# ← define one or more events here
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}   # ← also allow manual runs

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: utm_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Build Docker image
        run: docker build -t utm-backend .

      - name: Run migrations
        env:
          DATABASE_URL: postgresql://postgres:password@localhost:5432/utm_db
        run: |
          docker run --rm -e DATABASE_URL utm-backend alembic upgrade head

      - name: Run tests
        env:
          DATABASE_URL: postgresql://postgres:password@localhost:5432/utm_db
        run: |
          docker run --rm -e DATABASE_URL utm-backend pytest --maxfail=1 -q
