# .github/workflows/ci.yaml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: ./.github/actions/checkout

      - name: Setup Python
        uses: ./.github/actions/setup-python
        with:
          python-version: '3.13'
